version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    
    #environment:
    #   - DB_ENGINE=django.db.backends.postgresql
    #   - POSTGRES_DB=foodgram # имя БД
    #   - POSTGRES_USER=postgres # логин к БД
    #  - POSTGRES_PASSWORD=sec_postgres # пароль к БД
    #   - DB_HOST=db # название сервиса (контейнера)
    #   - DB_PORT=5432 # порт для подключения к БД
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build: ../backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
      image: nginx:1.21.3-alpine
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ../frontend/build:/usr/share/nginx/html/
        - ../docs/:/usr/share/nginx/html/api/docs/
        - static_value:/var/html/
        - media_value:/var/html/
      depends_on:
        - backend
      container_name: foodgram_nginx

volumes:
  postgres_data:
  static_value:
  media_value: